### ISSUE TITLE
what's the difference between'cv::fisheye::undistortPoints()' and 'cv::Point3f KannalaBrandt8::unproject()' ?

### ISSUE THREAD

**Issue by flyaudio** [UZ-SLAMLab/ORB_SLAM3#153]
`cv::fisheye::undistortPoints()` 
is used in function
`bool KannalaBrandt8::ReconstructWithTwoViews()`

I checked the source code in OpenCV,    `cv::fisheye::undistortPoints()`   seems the same as      `cv::Point3f KannalaBrandt8::unproject()`

my question is: What's the difference bewteen these 2 functions ?

**Comment by jjgr3496** [comment]
Hi @flyaudio,

Those functions, while some parts of them may be similar, are designed for different purposes:

-  `cv::fisheye::undistortPoints()` is a tool for undistorting features extracted in the fisheye image so they follow a projective  camera. In other words, this functions takes a set of KeyPoints extracted in the fisheye image and outputs the image coordinates of these points as if they were seen by a projective camera. We need this function for initializing the map with a monocular fisheye camera as computing a fundamental matrix with fisheye images is not trivial.

- `cv::Point3f KannalaBrandt8::unproject()` takes a point in the image and unprojects it to the projecting ray that conects the optical center of the camera with the 3D position of the observed point. This one is used when we need to triangulate a 3D points from observations taken from different images.

Please note that both functions involve, up to some point, to correct the fisheye distortion (that is the inverse of the camera projection function). That's why some parts are similar.

If you have further questions, please reopen this issue!
