### ISSUE TITLE
Stuck after loading first frame [id last: 0 id curr: 1] (mono_kitti and mono_tum)

### ISSUE THREAD

**Issue by GabHoo** [UZ-SLAMLab/ORB_SLAM3#169]
Hi there,
I am very new to this whole thing.

Basically I am trying to run my own sequences with both mono_tum and mono_kitti. 
Frames are from a video that I took with my phone camera. I calibrated it, created a proper timestamp file and called everything with the proper name in order for it to run BUT when I start it with all the parameters it get stuck after loading on the screen the first frame and placing on the map one single keyframe symbol. 
I wonder if it could be only very VERY slow since if I let it compute for some time the very last line that you see on the screenshot appears.

It could be a problem with loading the frames or something caused by a poor calibration of the camera [did that with the OpenCV class etcc] (?) but I feel such things would have given out proper error messages rather then this scenario.

anyway here is the console, as I said **the very last line comes out after lots of time** and with more waiting "id last=0 id curr=2" joins as well. Also fps value doesn't really matter I guess bc at the time I was testing it with variable number and still...

![Screenshot from 2020-10-26 01-11-22](https://user-images.githubusercontent.com/56197287/97245263-f71bf700-17fa-11eb-992a-6c49804118f3.png)

**Comment by richard-elvira** [comment]
That happens when the timestamp of the current frame and the previous frame are very close in time, in the realesed case when the time difference between the timestamps is less than 1 unit. I don't know which time units are using but the problem comes to that. 

Try to change the timestamps, I recomend you to use at leas milliseconds.

If you can avoid the timestamp check, you can modify the line 1422 in Tracking.cc
