### ISSUE TITLE
Does anybody run kitti dataset? How about the performance?

### ISSUE THREAD

**Issue by yafei-liu** [UZ-SLAMLab/ORB_SLAM3#4]

**Comment by cnqiangfu** [comment]
Compared with other VIO systems, I guess ORB-SLAM3 is better at round-trip indoor scenes because of the use of local BA.

**Comment by richard-elvira** [comment]
We have processed Kitti dataset with Stereo sensor, the results are similar to the reported results in [ORB-SLAM2](https://128.84.21.199/pdf/1610.06475.pdf). We obtain a better result only in the sequence 09, because a new Loop Closing is detected in ORB-SLAM3 as a result, the ATE is reduced from 3.2m to 1.6m.
