### ISSUE TITLE
Failed to initialize monocular slam

### ISSUE THREAD

**Issue by Chatoyant19** [UZ-SLAMLab/ORB_SLAM3#49]
Hi,
When I run monocular ORB-SLAM on my camera, it always fails to be initialized successfully. I found that most of the time because the value of nsimilar is equal to 2 so that cannot reconstruct fundamental matrix.
I'm sure I have correct camera intrinsic. And besides, is there any other parameters needs to modify?
Can you tell me what should I do?
Thank you very much.

**Comment by liangxiao05** [comment]
Hi,have you solved this?
I met the same problem，always shown "TRYING TO INITIALIZE"，and no keypoints extracted were shown in the image.

**Comment by jdtardos** [comment]
If it's a  monocular camera, translate the camera, don't perform pure rotations.
If it still fails to initialize, please, post images of your initialization failures.

**Comment by Chatoyant19** [comment]
@jdtardos 
Thank you for the answer.
yes, it's a monocular camera, but the reason for the initialization failure is not pure rotations. The trajectory path I collected is similar to kitti sequence 03.
I tried change my image encoding format from BAYER_RGGB8 to BGR8 and other format，it can be initialized Occasionally. But most of the time it's not useful.
I output some values in initialization part and found that the numbers of matched keypoints are sufficient. The reason is the ReconstructH and ReconstructF, they always return false So that it can't be initialized. Maybe I should modify which parameters to fix the problem.

**Comment by jdtardos** [comment]
You could try to increase 0.7 to 0.9 in this code:
    if(nGood1>0.7*maxGood)
        nsimilar++;
    if(nGood2>0.7*maxGood)
        nsimilar++;
    if(nGood3>0.7*maxGood)
        nsimilar++;
    if(nGood4>0.7*maxGood)
        nsimilar++;
Please, let us know if this improves your initialization.

**Comment by sandeepnmenon** [comment]
I am facing the same issue for my camera. Monocular camera is not getting initialise because `ReconstructF` always returns false. I increased the ratio to 0.9, but still the same. I see the values for the nGood and maxGood I get are
```
nMinGood: 539 
maxGood: 599 nGood1: 0 nGood2: 599 nGood3: 0 nGood4 599
nMinGood: 447 - 447.30000000000001
maxGood: 497 nGood1: 0 nGood2: 497 nGood3: 0 nGood4 497
nMinGood: 447 - 447.30000000000001
maxGood: 497 nGood1: 0 nGood2: 497 nGood3: 0 nGood4 497
nMinGood: 348 - 348.30000000000001
maxGood: 387 nGood1: 387 nGood2: 0 nGood3: 386 nGood4 0
```

Also, if I comment out the nsimilar check, then the parallax checks fail. All the parallaxes returned from CheckRT are less than 0.5 and faile to meet the minParallax=1 criteria.

What could be the issue with my data.

Sample data
![0](https://user-images.githubusercontent.com/11742991/143863681-c9b38c06-b1b9-4a59-ba3e-03a263021966.png)
![1](https://user-images.githubusercontent.com/11742991/143863694-00805f42-1801-479a-bca3-a051ad559066.png)
