### ISSUE TITLE
coordinate system of ORB_SLAM3 ?

### ISSUE THREAD

**Issue by zoldaten** [UZ-SLAMLab/ORB_SLAM3#681]
hi !
following the Paper i saw this picture:
![Screenshot_1](https://user-images.githubusercontent.com/29411817/202852699-fe21f1d2-73cc-4886-b11c-4b87548de26b.jpg)
camera axis:
Y camera looks - down;
X camera - right;
Z camera - forward.

IMU axis:
Y camera looks - right;
X camera - up;
Z camera - forward.

so the questions are:
1.should the whole system of camera-imu be calibrated with Kalibr as above picture says or
the axis of both should be in the same directions ?
2.which distance from camera to imu should be (to mount on robot or somewhere) and can it be changed ?

**Comment by WFram** [comment]
If you use Kalibr for Camera-IMU extrinsic calibration, in order to run ORB-SLAM3 in Stereo-Inertial mode you need to set two matrices:
1) `IMU.T_b_c1`: this is the transformation from left camera frame to IMU frame (left camera pose w.r.t. IMU frame). In report from Kalibr it corresponds to `T_ic:  (cam0 to imu0)`.
2) `Stereo.T_c1_c2`: this is the transformation from right camera to left camera (right camera pose w.r.t. left camera frame). To get this transformation, the `Baseline (cam0 to cam1)` from Kalibr should be inverted. Here assumed the left camera corresponds to `cam0`.

**Comment by zoldaten** [comment]
@WFram thanks.
so there is no matter how i will place IMU (in which direction) before calibration  matrices will do the job  after calibration ?

**Comment by WFram** [comment]
No matter. I guess you can run it even without a prior knowledge about IMU axes orientation itself. Because the only thing you need is to know a relative transformation from camera to IMU, which can be provided by Kalibr (as an example).

**Comment by zoldaten** [comment]
got it. thanks!
